fancybox: false
show_category_count: true

menu: 
  - page: home
    directory: .
  - page: archive
    directory: archives/
#  - page: about
#    directory: about/

widgets:
  - category
  - tag
  - links

links:
  - title: dedicatus545
    url: https://cnblogs.com/dedicatus545
  - title: sshockwave
    url: https://blog.sshockwave.net
  - title: DCDCbigbig
    url: https://www.cnblogs.com/dcdcbigbig/
  - title: Jackyhh
    url: https://www.cnblogs.com/JackyhhJuRuo/